language: node_js
node_js:
  - node

install: 
  - npm ci

script:
  - npm run build:lib
  - npm run build:docs

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master